stages:
  - build_image

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"


build_image:
  stage: build_image
  image: docker:latest
  before_script:
    - echo "DOCKER_IMAGE_NAME:${DOCKER_IMAGE_NAME}"
    - echo "LOCAL_IMAGE_NAME:${LOCAL_IMAGE_NAME}"
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always   # Always build for the main branch
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always   # Build for any non-main branch
    - when: never    # Default: skip if no conditions match
  script:
    - echo "DOCKER_IMAGE_NAME:${DOCKER_IMAGE_NAME}"
    - echo "LOCAL_IMAGE_NAME:${LOCAL_IMAGE_NAME}"
  artifacts:
    paths:
      - Dockerfile
    expire_in: 30 days

