stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days

test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn test