apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: ipm-app-backend
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: ipm-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: ipm-app
    spec:
      containers:
        - name: ipm-app
          # Run this image
          image: saurav3232/ipm:latest

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-ipm-app
spec:
  ports:
    # Accept traffic sent to port 8080
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: ipm-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer